# Generated by Django 3.1 on 2020-08-14 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date/Time when the record has been created')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Last Date/Time when the record has been updated')),
                ('name', models.CharField(max_length=10, verbose_name='Género')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date/Time when the record has been created')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Last Date/Time when the record has been updated')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('matriname', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('carrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_carrer', to='carrers.carrer', verbose_name='Arma')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_gender', to='candidates.gender', verbose_name='Genero')),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
