# Generated by Django 3.1 on 2020-08-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrer',
            name='places',
        ),
        migrations.AddField(
            model_name='carrer',
            name='places_h',
            field=models.IntegerField(default=0, verbose_name='Número de lugares disponibles para hombres.'),
        ),
        migrations.AddField(
            model_name='carrer',
            name='places_m',
            field=models.IntegerField(default=0, verbose_name='Número de lugares disponibles para mujeres.'),
        ),
    ]
